# Generated by Django 3.1.1 on 2020-10-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('lat', models.CharField(max_length=150)),
                ('lon', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.restaurant'),
        ),
    ]
