# Generated by Django 3.1.1 on 2020-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20201110_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='region',
            field=models.CharField(max_length=150),
        ),
    ]
