# Generated by Django 3.1.1 on 2020-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='special_address_name',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
