# Generated by Django 3.1.3 on 2021-03-23 07:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_activateusercode_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/natan/Desktop/celavie/foodDeliverBkEnd/media'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTagSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageAndTextSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/natan/Desktop/celavie/foodDeliverBkEnd/media'), upload_to='')),
                ('top_images', models.ManyToManyField(to='UserManagement.ImagesSettings')),
            ],
        ),
    ]
