# Generated by Django 3.1.3 on 2021-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_announcementsettings_imageandtextsettings_imagessettings_metatagsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberandEmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
