# Generated by Django 3.1.3 on 2021-03-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_phonenumberandemailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageandtextsettings',
            name='logo',
        ),
    ]
