# Generated by Django 3.1.3 on 2021-03-23 09:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_remove_imageandtextsettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/natan/Desktop/celavie/foodDeliverBkEnd/media'), upload_to='')),
            ],
        ),
    ]
