# Generated by Django 3.1.3 on 2021-03-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0012_logosettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumberandEmailSettings',
            new_name='BasicSettings',
        ),
    ]
