# Generated by Django 3.1.3 on 2021-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
