# Generated by Django 3.1.3 on 2021-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phoneNo',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
