# Generated by Django 3.1.7 on 2021-05-01 11:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20210302_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/natan/myproject/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/natan/myproject/media'), upload_to=''),
        ),
    ]
